package utility;

import java.util.Random;

/**
 * Utilities class for searching algorithms.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class SearchingUtilities
{
    /**
     * Generates a random array of integers. This is useful
     * for testing searching routines.
     *
     * @param size the size of the array to create
     * @param low the minimum value in the array
     * @param high the maximum value in the array
     * @return the newly created array
     */
    public static int[] generateRandomArray(int size, int low, int high)
    {
        Random random = new Random();
        int[] array = new int[size];

        for (int i = 0; i < array.length; i++)
        {
            array[i] = low + random.nextInt(high - low + 1);
        }

        return array;
    }
}